name: My Workflow Chain

on: # Webhook triggers
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          script: |
            const { default: sayHi } = await import('${{ github.workspace }}/.github/workflows/chain/say-hi.js')

            sayHi({github, context})

  job_2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          script: |
            const { default: sayHi } = await import('${{ github.workspace }}/.github/workflows/chain/say-hi.js')

            sayHi({github, context})

  job_3:
    runs-on: ubuntu-latest
    needs: job_1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          script: |
            const { default: sayHi } = await import('${{ github.workspace }}/.github/workflows/chain/say-hi.js')

            sayHi({github, context})

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          script: |
            const { default: sayHi } = await import('${{ github.workspace }}/.github/workflows/chain/say-hi.js')

            sayHi({github, context})
