name: My Workflow Chain

on: # Webhook triggers
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { default: sayHi } = await import('${{ github.workspace }}/.github/workflows/chain/say-hi.js')

            sayHi({github, context})
      - run: echo "Hello!"
