name: My Periodic Workflow

on:
  schedule:
    # Syntax:
    #    |    *    |    *    |       *       |        *        |      *
    #    | minutes |  Hours  | Days of Month |      Month      | Days of Week
    #    |  0-59   |  0-23   |     1-31      |  1-12 / JAN-DEC | 0-6 / SUN-SAT
    - cron: "*/5 * * * *"
    #       hours
    # - cron: "30 */3 * * *"
    #       days
    # - cron: "30 9 */2 * *"
    #       working hours
    # - cron: "0 9-18 * * 1-5"
    #       not wednesdays or fridays
    # - cron: "0 * * * 1,2,4"

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "I run periodically!"
