name: Custom Action Workflow

on: [push]

jobs:
  docker-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo to use local action
        uses: actions/checkout@v4

      - name: Run custom action
        uses: ./.github/actions/action-docker-sh
        id: hello
        with:
          who-to-greet: "@druue"

      - name: Output the answer
        run: echo "The answer is ${{ steps.hello.outputs.answer }}"

      - name: Test the container
        if: ${{ steps.hello.outputs.answer != 42 }}
        run: |
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
          exit 1

  js-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo to use local action
        uses: actions/checkout@v4

      - name: Run custom action
        uses: ./.github/actions/action-js
        id: hello
        with:
          who-to-greet: "@druue"

      - name: Output the answer
        run: echo "The answer is ${{ steps.hello.outputs.answer }}"

  js-script-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Run custom action
        uses: ./.github/actions/action-js-runner
        id: hello
        with:
          who-to-greet: "@druue"

      - name: Output the answer
        run: echo "The answer is ${{ steps.hello.outputs.answer }}"
