name: Custom Action Workflow

on: [push]

jobs:
  custom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo to use local action
        uses: actions/checkout@v4

      - run: ls

      - name: Run custom action
        id: my-first-action
        uses: ./
        with:
          who-to-greet: "@druue"

      - name: Output the answer
        run: echo "The answer is ${{ steps.my-first-action.outputs.answer }}"

      - name: Test the container
        if: ${{ steps.my-first-action.outputs.answer != 42 }}
        run: |
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
          exit 1
